services:
  app:
    container_name: stackoverflow
    image: stackoverflow
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: unless-stopped

  web:
    container_name: web
    image: schoolstackapp
    build:
      context: ./SchoolStackApp
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on:
      - app
    restart: unless-stopped

  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    configs:
      - source: init.sql
        target: /docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=catsarecool
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass

configs:
  pgpass:
    file: ./resources/pgadmin4/pgpass
  servers.json:
    file: ./resources/pgadmin4/servers.json
  init.sql:
    file: ./resources/postgres/init.sql