services:
  app:
    container_name: stackoverflow
    image: stackoverflow
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=catsarecool

